services:
  prometheus:
    image: prom/prometheus:v2.54.1
    restart: unless-stopped
    volumes:
      - "prom_data:/prometheus"
      - "./prometheus.yml:/etc/prometheus/prometheus.yml:ro"
    ports:
      - 9090:9090
    networks:
      - prom_net
    extra_hosts:
      - "rpi-host:192.168.38.1"

  node:
    image: prom/node-exporter:v1.8.2
    command:
      - "--path.rootfs=/host"
    pid: host
    restart: unless-stopped
    volumes:
      - "/:/host:ro,rslave"
    expose:
      - 9100
    network_mode: host

  grafana:
    image: grafana/grafana-oss:11.2.2
    restart: unless-stopped
    volumes:
      - "grafana_data:/var/lib/grafana"
    ports:
      - 3000:3000
    networks:
      - prom_net

volumes:
  prom_data: {}
  grafana_data: {}

networks:
  prom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.38.0/24
          gateway: 192.168.38.1
