services:
  rss:
    container_name: rss
    image: mskrzypietz/rss:1.0.42
    restart: unless-stopped
    depends_on:
      - nats
    volumes:
      - logs:/app/logs
    environment:
        - DB_URL=${DB_URL}
        - ORIGIN_URL=${ORIGIN_URL}
        - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
        - NATS_CONNECTION_STRING=${NATS_CONNECTION_STRING}

  tunnel:
    container_name: rss-cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
        - TUNNEL_TOKEN=${RSS_CF_TUNNEL_TOKEN}
    depends_on:
      - rss

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - loki-data:/loki
    depends_on:
      - rss

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yaml
      - logs:/var/log/app
      - promtail-data:/tmp
    command: -config.file=/etc/promtail/config.yaml
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - loki

  nats:
    image: nats:2
    container_name: nats-server
    ports:
      - "8222:8222"
    command: ["--js", "--store_dir=/data", "-m", "8222"]
    volumes:
      - nats-data:/data
    restart: unless-stopped

volumes:
  logs:
  loki-data:
  promtail-data:
  grafana-data:
  nats-data:

